# Generated by Django 5.0.2 on 2024-03-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_alter_todolist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todo_list',
        ),
    ]
