# Generated by Django 5.0.2 on 2024-03-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0016_remove_todo_todo_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
