# Generated by Django 5.0.2 on 2024-03-06 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0018_alter_todo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todos.todo_list'),
        ),
    ]
